#!/usr/bin/env php
<?php

// Find autoloader
$autoloadPaths = [
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../vendor/autoload.php',
];

$autoloaded = false;
foreach ($autoloadPaths as $file) {
    if (file_exists($file)) {
        require $file;
        $autoloaded = true;
        break;
    }
}

if (!$autoloaded) {
    fwrite(STDERR, "Autoload file not found. Run 'composer install' first.\n");
    exit(1);
}

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use TestrailTools\Command\BuildInfoCommand;
use TestrailTools\Command\UpdateWorkflowCommand;
use TestrailTools\Command\PrepareCommitCommand;
use TestrailTools\Command\InstallHookCommand;
use TestrailTools\Command\SelfUpdateCommand;
use TestrailTools\Command\TriggerBuildCommand;
use TestrailTools\Service\AutoUpdateChecker;

$application = new Application('Branch Tools', '1.1.0');

// Register commands
$application->add(new BuildInfoCommand());
$application->add(new UpdateWorkflowCommand());
$application->add(new PrepareCommitCommand());
$application->add(new InstallHookCommand());
$application->add(new SelfUpdateCommand());
$application->add(new TriggerBuildCommand());

// Check for updates before running any command (except self-update itself)
$input = new ArgvInput();
$output = new ConsoleOutput();

// Get the command name being executed
$commandName = $input->getFirstArgument();

// Skip auto-update check for these commands
$skipCommands = ['self-update', 'list', 'help', '--version', '-V', '--help', '-h'];

if (!in_array($commandName, $skipCommands, true)) {
    $autoUpdateChecker = new AutoUpdateChecker($application->getVersion());
    $questionHelper = $application->getHelperSet()->get('question');
    
    // Check for updates and prompt if available
    // If update was installed, this returns false to stop execution
    $shouldContinue = $autoUpdateChecker->checkAndPrompt($input, $output, $questionHelper);
    
    if (!$shouldContinue) {
        // Update was installed, exit gracefully
        exit(0);
    }
}

$application->run();
